### ISSUE TITLE
TODO list for Blockchain 2020

### ISSUE THREAD

**Issue by jkrvivian** [jkrvivian/MyThesis#39]
## vvn
* [x] Chap 4: Reduce Chap4-C
* [x] Chap 5: 
   * [x] Refactor 5-A, B, C, D
   * [x] Rewrite  Refund
* [x] Chap 6: 
   * [x] Refactor 6-A
   * [x] Add Gas Evaluation
* [x] Reference
   * [x] Add access time to online refs
   * [x] Remove IOTA whitepaper ref
