### ISSUE TITLE
TODO list v2

### ISSUE THREAD

**Issue by jkrvivian** [jkrvivian/MyThesis#49]
* [x] Re-evaluate writing: MAM looks like our work :sob: 
* [x] Add more explanation of `Why MAM ?` in the first paragraph of Chap 4 => move to Chap 3, choice of data storage
* [x] Add more description of digital rights `Why bind subscription and data storage?` => note: add in Chap 3, smart contract
* [x] Improve Conclusion
* [x] Fix lengthy Abstract
